### PR TITLE
Remove the Regex lesson

### PR DESCRIPTION
**Pull request by Dangeranger**

### CODE REVIEW

**Comment by alexch** [comment]
Did you remove this in order to add it elsewhere? Or do you think it's not worth it to teach regexes in a lecture?

**Comment by Dangeranger** [comment]
When we spoke about the lesson you mentioned that you thought Regex exercises could be done as pre-work and then woven into other lessons within the curriculum rather than have a dedicated lesson(s). Do you no longer want to do that?

**Comment by alexch** [comment]
gotcha, thx

**Comment by Dangeranger** [comment]
@alexch This has been rebased on top of current master and is ready for final review and merge.

**Pull request merged**
